name: indestructible-items
version: '1.0-SNAPSHOT'
main: ru.nyansus.mc.indestructibleItems.IndestructibleItems
api-version: '1.21'

commands:
  indestructible:
    description: Mark item as indestructible or remove the property
    usage: /<command> <add|remove|check>
    permission: indestructibleitems.use

permissions:
  indestructibleitems.use:
    description: Allows using /indestructible command
    default: op
